name: coverage

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov playwright pytest-playwright
          python -m playwright install --with-deps
      - name: Run Setup.py
        run: |
          python -m setup build_ext --inplace --compile-with-cython-linetrace
      - name: Tests
        run: |
          pytest --cov persistable
      - name: Upload coverage results
        uses: codecov/codecov-action@v4

