name: tests

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest playwright pytest-playwright
          python -m playwright install --with-deps
      - name: Run Setup.py
        run: |
          python -m setup build_ext --inplace
      - name: Run test 
        run: |
          pytest . --tracing=retain-on-failure
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/


  test-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest playwright pytest-playwright
          python -m playwright install --with-deps
      - name: Run Setup.py
        run: |
          python -m setup build_ext --inplace
      - name: Run test 
        run: |
          pytest .


  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest playwright pytest-playwright
          python -m playwright install --with-deps
      - name: Run Setup.py
        shell: bash -l {0}
        run: |
          python -m setup build_ext --inplace
      - name: Run test 
        shell: bash -l {0}
        run: |
          pytest .
